DCMEDIA_SITE = $(TOPDIR)/../external/dcmedia
DCMEDIA_SITE_METHOD = local
DCMEDIA_INSTALL_STAGING = YES

DCMEDIA_DEPENDENCIES += mpp
DCMEDIA_DEPENDENCIES += alsa-lib
DCMEDIA_DEPENDENCIES += common_algorithm
DCMEDIA_DEPENDENCIES += libv4l
DCMEDIA_DEPENDENCIES += linux-rga
DCMEDIA_DEPENDENCIES += rknpu
DCMEDIA_DEPENDENCIES += rockx
DCMEDIA_DEPENDENCIES += libdrm
DCMEDIA_DEPENDENCIES += live555
DCMEDIA_DEPENDENCIES += minilogger
DCMEDIA_DEPENDENCIES += rk_oem

# 컴파일중 경고를 에러로 처리함
#DCMEDIA_CONF_OPTS = -DWARNINGS_AS_ERRORS=ON

#DCMEDIA_DEPENDENCIES += rkmedia

#DCMEDIA_POST_INSTALL_TARGET_HOOKS += DCMEDIA_INSTALL_TARGET_REMOVE_HOOK
#DCMEDIA_DEPENDENCIES += rk_oem
#DCMEDIA_CONF_OPTS += -DCONFIG_OEM=1
#DCMEDIA_INSTALL_TARGET_OPTS = DESTDIR=$(BR2_PACKAGE_RK_OEM_INSTALL_TARGET_DIR) install/fast
#ifeq ($(BR2_PACKAGE_RK_OEM), y)
#	DCMEDIA_INSTALL_TARGET_OPTS = DESTDIR=$(BR2_PACKAGE_RK_OEM_INSTALL_TARGET_DIR) install/fast
#	DCMEDIA_DEPENDENCIES += rk_oem
#endif

$(eval $(cmake-package))
